# Generated by Django 4.1.7 on 2023-03-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_board_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="board", options={"ordering": ["position"]},),
    ]
