# Generated by Django 4.1.7 on 2023-03-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id_board", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("position", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id_item", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("position", models.IntegerField()),
                (
                    "id_board",
                    models.ForeignKey(
                        db_column="id_board",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.board",
                    ),
                ),
            ],
        ),
    ]
