# Generated by Django 4.1.7 on 2023-03-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_item_id_board"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="id_board", new_name="board",
        ),
    ]
